tasks:
  build-deps:
    runner: razorci/ruby
    steps:
    - checkout
    - commands:
      - apt-get update
      - apt-get install -y build-essential libpq-dev nodejs
      - COPY Gemfile /app/Gemfile
      - COPY Gemfile.lock /app/Gemfile.lock
      - cd /app && bundle install --without test development