tasks:
  build-deps:
    runner: razorci/ruby
    steps:
    - docker-build:
      image: razorci/docs
      push: true
      tags: ["${CI_COMMIT_SHA}", "latest"]
      dockerfile: Dockerfile
      context: .