tasks:
  build:
    runner: razorci/ruby
    steps:
    - checkout
    - docker/build:
        image: quay.io/gnulinooks/demo
        push: true
        tags: ["${CI_COMMIT_SHA}", "latest"]
        dockerfile: Dockerfile
        context: .